---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
      - id: check-json
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
