# Welcome to Jekyll!
title: DL Resume
url: https://dennislapchenko.github.io
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: en                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
theme_color: "#b0dd52"      # your favorite theme color
allow_search_engines: false  # allow search engines indexing your resume
analytics:
  google: G-GHFWPHDLGR
